name: Release MONET Platform
on:
  push:
    tags: ['v*']

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Build packages
        run: |
          pnpm build
          
      - name: Debug - Check build outputs
        run: |
          echo "=== Frontend build output ==="
          ls -la packages/client/
          echo "=== Frontend dist directory ==="
          ls -la packages/client/dist/ || echo "No dist directory in client"
          echo "=== Backend build output ==="
          ls -la packages/core/
          echo "=== Backend dist directory ==="
          ls -la packages/core/dist/ || echo "No dist directory in core"
          
      - name: Create deployment packages
        run: |
          # Frontend package - just the built static files
          echo "=== Creating frontend package ==="
          cd packages/client
          if [ ! -d "dist" ]; then
            echo "ERROR: No dist directory found in client package"
            exit 1
          fi
          mkdir -p ../../frontend-deploy
          cp -r dist/* ../../frontend-deploy/
          cd ../../frontend-deploy
          ls -la
          zip -r ../monet-frontend.zip .
          cd ..
          echo "Frontend package created: $(ls -la monet-frontend.zip)"
          
          # Backend package - single Azure Function
          echo "=== Creating backend package ==="
          cd packages/core
          
          # Check if dist directory exists
          if [ ! -d "dist" ]; then
            echo "ERROR: No dist directory found in core package"
            echo "Available files:"
            ls -la
            exit 1
          fi
          
          # Create Azure Functions deployment structure
          mkdir -p api-deploy
          echo "Created api-deploy directory"
          
          # Copy compiled JavaScript files
          cp -r dist/* api-deploy/
          echo "Copied dist files to api-deploy:"
          ls -la api-deploy/
          
          # Copy package.json
          if [ ! -f "package.json" ]; then
            echo "ERROR: No package.json found in core package"
            exit 1
          fi
          cp package.json api-deploy/
          echo "Copied package.json"
          
          cd api-deploy
          echo "Current directory: $(pwd)"
          echo "Files in api-deploy:"
          ls -la
          
          # Install production dependencies
          echo "Installing production dependencies..."
          npm install --production
          if [ $? -ne 0 ]; then
            echo "ERROR: npm install failed"
            exit 1
          fi
          echo "Dependencies installed successfully"
          
          # Create host.json for single function with no route prefix
          echo "Creating host.json..."
          cat > host.json << 'EOF'
          {
            "version": "2.0",
            "extensionBundle": {
              "id": "Microsoft.Azure.Functions.ExtensionBundle",
              "version": "[4.*, 5.0.0)"
            },
            "functionTimeout": "00:05:00",
            "http": {
              "routePrefix": ""
            }
          }
          EOF
          echo "host.json created"
          
          # Create function.json for the single Express wrapper function
          echo "Creating function directory and config..."
          mkdir -p expressApp
          cat > expressApp/function.json << 'EOF'
          {
            "bindings": [
              {
                "authLevel": "anonymous",
                "type": "httpTrigger",
                "direction": "in",
                "name": "req",
                "methods": ["get", "post", "put", "delete", "patch", "options"],
                "route": "{*segments}"
              },
              {
                "type": "http",
                "direction": "out",
                "name": "res"
              }
            ],
            "scriptFile": "../function-wrapper.js"
          }
          EOF
          echo "function.json created"
          
          # Debug: Show final structure
          echo "=== Final api-deploy structure ==="
          find . -type f -name "*.js" | head -10
          echo "=== Key files check ==="
          ls -la function-wrapper.js || echo "WARNING: function-wrapper.js not found"
          ls -la host.json || echo "WARNING: host.json not found"
          ls -la expressApp/function.json || echo "WARNING: function.json not found"
          
          # Create the deployment package
          echo "Creating ZIP package..."
          zip -r ../../monet-api.zip . -x "node_modules/.cache/*"
          if [ $? -ne 0 ]; then
            echo "ERROR: Failed to create ZIP package"
            exit 1
          fi
          
          cd ../..
          echo "Backend package created: $(ls -la monet-api.zip)"
          
      - name: Verify packages before release
        run: |
          echo "=== Final package verification ==="
          ls -la monet-*.zip
          echo "Frontend package size: $(du -h monet-frontend.zip)"
          echo "Backend package size: $(du -h monet-api.zip)"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            monet-frontend.zip
            monet-api.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}