name: Release MONET Platform
on:
  push:
    tags: ['v*']

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js & pnpm
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
        
      - name: Build packages
        run: pnpm build
          
      - name: Create deployment packages
        run: |
          # Create a releases directory in the root
          mkdir -p releases
          
          # Frontend package
          echo "=== Creating frontend package ==="
          cd packages/client
          mkdir -p ../../releases/frontend-deploy
          cp -r dist/* ../../releases/frontend-deploy/
          cd ../../releases/frontend-deploy
          zip -r ../monet-frontend.zip .
          cd ../..
          echo "Frontend package created"
          
          # Backend package
          echo "=== Creating backend package ==="
          cd packages/core
          
          # Create Azure Functions deployment structure
          mkdir -p ../../releases/api-deploy
          
          # Copy compiled JavaScript files
          cp -r dist/* ../../releases/api-deploy/
          cp package.json ../../releases/api-deploy/
          
          cd ../../releases/api-deploy
          
          # Install production dependencies
          npm install --production
          
          # Create host.json
          cat > host.json << 'EOF'
          {
            "version": "2.0",
            "extensionBundle": {
              "id": "Microsoft.Azure.Functions.ExtensionBundle",
              "version": "[4.*, 5.0.0)"
            },
            "functionTimeout": "00:05:00",
            "http": {
              "routePrefix": ""
            }
          }
          EOF
          
          # Create function directory and config
          mkdir -p expressApp
          cat > expressApp/function.json << 'EOF'
          {
            "bindings": [
              {
                "authLevel": "anonymous",
                "type": "httpTrigger",
                "direction": "in",
                "name": "req",
                "methods": ["get", "post", "put", "delete", "patch", "options"],
                "route": "{*segments}"
              },
              {
                "type": "http",
                "direction": "out",
                "name": "res"
              }
            ],
            "scriptFile": "../function-wrapper.js"
          }
          EOF
          
          # Create the deployment package in releases directory
          zip -r ../monet-api.zip . -x "node_modules/.cache/*"
          
          # Go back to root
          cd ../..
          
      - name: Verify packages
        run: |
          echo "=== Package verification ==="
          ls -la releases/
          du -h releases/monet-*.zip
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            releases/monet-frontend.zip
            releases/monet-api.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}