name: Release MONET Platform

on:
  push:
    tags: ['v*']

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Frontend Build Step ---
      - name: Setup Node.js and pnpm for Frontend
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install Frontend Dependencies
        run: pnpm install
      - name: Build Frontend
        run: pnpm --filter monet-client build

      # --- Python Backend Packaging Step ---
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create API Deployment Package
        run: |
          # 1. Create a clean staging directory
          mkdir -p staging

          # 2. Copy the entire Python app folder from the core package
          echo "Copying Python backend application..."
          cp -r packages/core/app/* staging/
          
          # 3. Copy backend configuration files
          cp packages/core/host.json staging/
          cp packages/core/requirements.txt staging/
          cp packages/core/local.settings.json staging/
          
          # 4. Copy the built frontend into a 'frontend' subfolder
          echo "Copying built frontend files..."
          cp -r packages/client/dist staging/frontend

          # 5. Install Python dependencies directly into the staging folder
          echo "Installing production Python dependencies..."
          pip install --target="./staging" -r ./staging/requirements.txt

          # 6. Verify the final structure
          echo "Final structure in staging directory:"
          ls -lR staging

          # 7. Zip the contents of the staging directory
          echo "Zipping deployment package..."
          (cd staging && zip -r ../monet-api.zip .)
          
      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: monet-api.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}